export const REQUEST_SESSION = 'REQUEST_SESSION';
export const REQUEST_SESSION_SUCCESS = 'REQUEST_SESSION_SUCCESS';
export const COMPLETE_SESSION = 'COMPLETE_SESSION';
export const COMPLETE_SESSION_SUCCESS = 'COMPLETE_SESSION_SUCCESS';
