export const SESSION_REQUEST_TOKEN = 'SESSION_REQUEST_TOKEN';
export const SESSION_REQUEST_TOKEN_SUCCESS = 'SESSION_REQUEST_TOKEN_SUCCESS';
export const SESSION_REQUEST_TOKEN_ERROR = 'SESSION_REQUEST_TOKEN_ERROR';
