export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR';

export const TOGGLE_TO_WATCHLIST = 'TOGGLE_TO_WATCHLIST';
export const TOGGLE_TO_WATCHLIST_SUCCESS = 'TOGGLE_TO_WATCHLIST_SUCCESS';
export const TOGGLE_TO_WATCHLIST_ERROR = 'TOGGLE_TO_WATCHLIST_ERROR';
