export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_ERROR = 'FETCH_FAVORITES_ERROR';

export const TOGGLE_TO_FAVORITES = 'TOGGLE_TO_FAVORITES';
export const TOGGLE_TO_FAVORITES_SUCCESS = 'TOGGLE_TO_FAVORITES_SUCCESS';
export const TOGGLE_TO_FAVORITES_ERROR = 'TOGGLE_TO_FAVORITES_ERROR';
