export const FETCH_MY_LISTS = 'FETCH_MY_LISTS';
export const FETCH_MY_LISTS_SUCCESS = 'FETCH_MY_LISTS_SUCCESS';
export const FETCH_MY_LISTS_ERROR = 'FETCH_MY_LISTS_ERROR';

export const CREATE_MY_LIST = 'CREATE_MY_LIST';

export const DELETE_MY_LIST = 'DELETE_MY_LIST';
export const DELETE_MY_LIST_ERROR = 'DELETE_MY_LIST_ERROR';

export const TOGGLE_TO_LIST = 'TOGGLE_TO_LIST';
export const TOGGLE_TO_LIST_SUCCESS = 'TOGGLE_TO_LIST_SUCCESS';

export const CREATE_AND_ADD_TO_LIST = 'CREATE_AND_ADD_TO_LIST';
