export const FETCH_WATCHLIST = 'FETCH_WATCHLIST';
export const FETCH_WATCHLIST_SUCCESS = 'FETCH_WATCHLIST_SUCCESS';
export const FETCH_WATCHLIST_ERROR = 'FETCH_WATCHLIST_ERROR';

export const TOGGLE_TO_WATCHLIST = 'TOGGLE_TO_WATCHLIST';
export const TOGGLE_TO_WATCHLIST_SUCCESS = 'TOGGLE_TO_WATCHLIST_SUCCESS';
export const TOGGLE_TO_WATCHLIST_ERROR = 'TOGGLE_TO_WATCHLIST_ERROR';
