export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';

export const FETCH_TRENDING_MOVIES = 'FETCH_TRENDING_MOVIES';

export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SET_SEARCH_MOVIES_QUERY = 'SET_SEARCH_MOVIES_QUERY';
